local addon = _G.HoverToolTip
if not addon then return end

addon.defaults = {
	enable = true,
	alpha = 1,
	textAlpha = 1,
	scale = 1,
	hideBackdrop = true,
	statusBar = true,

	titleTextSize = 14,
	titleTextOutline = "SHADOWOUTLINE",
	bodyTextSize = 11,
	bodyTextOutline = "SHADOWOUTLINE",
	objectTitleTextSize = 14,
	objectBodyTextSize = 11,
	unitInfoAboveName = false,

	detailsKey = "NONE",
	detailsOnUnitFrames = false,
	hideQuestTitles = false,
	hideQuestObjectives = false,
	hideQuestPlayers = false,
	hidePlayerGuild = false,
	hidePlayerTitle = false,
	hidePlayerRealm = false,
	hidePlayerLevelRace = false,
	hidePlayerLevel = false,
	hidePlayerRace = false,
	hidePlayerClass = false,
	hidePlayerFaction = false,
	hidePlayerPvP = false,
	hidePlayerMount = false,
	hidePlayerTarget = false,
	hidePlayerRole = false,
	hideNPCLevel = false,
	hideNPCClassification = false,
	hideNPCCreatureType = false,
	hideNPCTitle = false,
	hideNPCAffiliation = false,
	hideNPCThreat = false,
	hideNPCTarget = false,
}
